In [1]:
import seaborn as sns
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,confusion_matrix
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [5]:
import pandas as pd

columns = ['sepal_length','sepal_width','petal_length','petal_width','species']

df = pd.read_csv(r"C:\Users\KIIT0001\Downloads\iris\iris.data", names=columns)

df.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [6]:
encoder=LabelEncoder()
df['species']=encoder.fit_transform(df['species'])
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [7]:
df = df[['sepal_length','petal_length','species']]

df.head()

   sepal_length  petal_length  species
0           5.1           1.4        0
1           4.9           1.4        0
2           4.7           1.3        0
3           4.6           1.5        0
4           5.0           1.4        0

In [10]:
X=df.iloc[:,0:2]
y=df.iloc[:,-1]

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)
clf=LogisticRegression(multi_class='multinomial')

clf.fit(X_train,y_train)
y_pred=clf.predict(X_test)
print(accuracy_score(y_test,y_pred))

0.9666666666666667

C:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

In [13]:
pd.DataFrame(confusion_matrix(y_test,y_pred))

    0  1  2
0  14  0  0
1   0  7  1
2   0  0  8

In [15]:
query=np.array([[3.4,2.7]])
clf.predict_proba(query)

C:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([[7.27325812e-01, 2.72261852e-01, 4.12335718e-04]])

In [16]:
clf.predict(query)

C:\Users\KIIT0001\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([0])

In [ ]:
from mlxtend.plotting import plot_decision_regions

plot_deciision_regions(x.values,y.values,clf,legend=2)

plt.xlabel('sepal')